//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Client.PosServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PosServices.IPosService")]
    public interface IPosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetProducts", ReplyAction="http://tempuri.org/IPosService/GetProductsResponse")]
        System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetProducts", ReplyAction="http://tempuri.org/IPosService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetCustomers", ReplyAction="http://tempuri.org/IPosService/GetCustomersResponse")]
        System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Customer> GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetCustomers", ReplyAction="http://tempuri.org/IPosService/GetCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Customer>> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SubmitOrder", ReplyAction="http://tempuri.org/IPosService/SubmitOrderResponse")]
        void SubmitOrder(Pos.Entities.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SubmitOrder", ReplyAction="http://tempuri.org/IPosService/SubmitOrderResponse")]
        System.Threading.Tasks.Task SubmitOrderAsync(Pos.Entities.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPosServiceChannel : Pos.Client.PosServices.IPosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PosServiceClient : System.ServiceModel.ClientBase<Pos.Client.PosServices.IPosService>, Pos.Client.PosServices.IPosService {
        
        public PosServiceClient() {
        }
        
        public PosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Product> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Product>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Customer> GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Pos.Entities.Customer>> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public void SubmitOrder(Pos.Entities.Order order) {
            base.Channel.SubmitOrder(order);
        }
        
        public System.Threading.Tasks.Task SubmitOrderAsync(Pos.Entities.Order order) {
            return base.Channel.SubmitOrderAsync(order);
        }
    }
}
